# -*- coding: utf-8 -*-
"""Alura 01. Introdução a data sciencei.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jqO9FJxinxmYY7LRL6y2MhaTnmHboOH1

#Analisando notas em geral
"""

import pandas as pd

notas = pd.read_csv("ratings.csv")
notas.head()

notas.shape

notas.columns=["usuarioId", "filmeId", "Nota", "Momento"]
notas.head()

notas['Nota'].unique()

notas['Nota'].value_counts()

notas['Nota'].mean()

notas.Nota.plot(kind= 'hist')

notas.Nota.describe()

import seaborn as sns

sns.boxplot(notas.Nota)

"""#Olhando os filmes"""

filmes = pd.read_csv ("movies.csv")

filmes.head()

notas.head()

"""#Analisando notas por filme

"""

notas.query('filmeId==1').Nota.mean()

notas.query('filmeId==2').Nota.mean()

notas.groupby('filmeId').mean()

media_por_filme = notas.groupby('filmeId').mean().Nota
media_por_filme.head()

"""#Visualizando por histograma/boxplot a Média por filme"""

media_por_filme.plot(kind='hist')

sns.boxplot(media_por_filme)

media_por_filme.describe()

sns.distplot(media_por_filme, bins= 10)

"""#Tipos de variáveis"""

import pandas as pd

tmdb = pd.read_csv('tmdb_5000_movies.csv')
tmdb.head()

tmdb.original_language.unique() #categoria nominal

tmdb['original_language'].value_counts().index

tmdb['original_language'].value_counts().values

contagem_de_lingua= tmdb['original_language'].value_counts().to_frame().reset_index()
contagem_de_lingua.columns=['original_language', 'total']
contagem_de_lingua.head()

"""#Visualizando categorias"""

import seaborn as sns
sns.barplot(x ='original_language', y= 'total', data = contagem_de_lingua)

import matplotlib.pyplot as plt
_ = plt.pie(contagem_de_lingua["total"], labels=contagem_de_lingua["original_language"], autopct="%1.1f%%")

total_por_lingua= tmdb['original_language'].value_counts()
total_geral = total_por_lingua.sum()

total_de_ingles= total_por_lingua.loc ['en']
total_do_resto = total_geral - total_de_ingles
print (total_de_ingles, total_do_resto)

dados = {
    'lingua': ['ingles', 'outros'],
    'total': [total_de_ingles, total_do_resto]
}
dados

pd.DataFrame(dados)

sns.barplot(x='lingua', y='total', data= dados)

plt.pie(dados['total'],labels=dados ['lingua'])

total_por_lingua_de_outros_filmes= tmdb.query("original_language != 'en'"). original_language.value_counts()
total_por_lingua_de_outros_filmes

